# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField(default=None, null=True)),
                ('serie', models.CharField(max_length=90)),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name=b'related object')),
                ('status', models.CharField(choices=[(b'Attended', b'ATTENDED'), (b'Canceled', b'CANCEL'), (b'Pending', b'PENDING')], max_length=20)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name=b'content type')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Branch', b'BRANCH'), (b'Company', b'COMPANY'), (b'Customer', b'CUSTOMER'), (b'Franchise', b'FRANCHISE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.UserProfile')),
                ('nickName', models.CharField(max_length=300)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.TextField(blank=True, max_length=20)),
            ],
            options={
                'permissions': (('is_branch', 'Es una sucursal'),),
            },
            bases=('backend.userprofile',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.UserProfile')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('identityDoc', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.TextField(blank=True, max_length=20)),
            ],
            options={
                'permissions': (('is_company', 'Es una empresa'),),
            },
            bases=('backend.userprofile',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.UserProfile')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('lastName', models.TextField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('identityDoc', models.IntegerField(unique=True)),
                ('homePhone', models.TextField(blank=True, max_length=20, null=True)),
                ('cellPhone', models.TextField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'permissions': (('is_customer', 'Es un cliente'),),
            },
            bases=('backend.userprofile',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='backend.State'),
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Company')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Brand')),
            ],
            options={
                'permissions': (('is_franchise', 'Es una franquicia'),),
            },
            bases=('backend.company',),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='backend.City'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branchCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.City'),
        ),
    ]
